"""LSD input file generator from NMR peak data."""

import importlib.resources
import re
from pathlib import Path

from ailsa.detection.models import SignalGroup
from ailsa.lsd.models import Hybridization, LSDAtom, LSDConstraint, LSDCorrelation, LSDProblem
from ailsa.models import PeakList1D, PeakList2D
from ailsa.processing.dept_guided_picker import DEPTGuidedResult


def parse_molecular_formula(formula: str) -> dict[str, int]:
    """Parse a molecular formula into element counts.

    Args:
        formula: Molecular formula like "C13H18O2"

    Returns:
        Dictionary of element -> count, e.g., {"C": 13, "H": 18, "O": 2}
    """
    counts: dict[str, int] = {}
    # Match element symbol (1-2 letters) followed by optional count
    pattern = r"([A-Z][a-z]?)(\d*)"
    for match in re.finditer(pattern, formula):
        element = match.group(1)
        count = int(match.group(2)) if match.group(2) else 1
        if element:  # Skip empty matches
            counts[element] = counts.get(element, 0) + count
    return counts


class LSDInputGenerator:
    """Generate LSD input files from NMR peak data.

    Converts peak lists from NMR experiments into LSD format:
    - 13C peaks → atom definitions (MULT)
    - HSQC peaks → direct C-H correlations
    - HMBC peaks → long-range C-H correlations
    - COSY peaks → H-H correlations
    """

    @staticmethod
    def emit_form(formula: str) -> str:
        """Emit a molecular-formula declaration as an LSD comment.

        LSD-3.4.9 rejects a bare `FORM` command with `error 102 - Unknown
        command name: FORM` (see .planning/findings/form-tolerance.md). The
        formula is therefore emitted as a comment (`; FORM <formula>`) which
        LSD silently ignores while remaining visible to human readers and
        inventory-block consumers.

        Args:
            formula: Molecular formula string, e.g. "C13H18O2"

        Returns:
            String like "; FORM C13H18O2" (LSD comment)
        """
        return f"; FORM {formula}"

    @staticmethod
    def emit_elim(n: int, m: int) -> str:
        """Emit a pyLSD ELIM command line.

        ELIM drops the correlation entirely. For 4J handling, use
        HMBC X Y 2 4 (set max_bonds=4 on LSDCorrelation).

        Args:
            n: First atom index
            m: Second atom index

        Returns:
            String like "ELIM 4 4"
        """
        return f"ELIM {n} {m}"

    @staticmethod
    def emit_shih(atom_idx: int, shift: float) -> str:
        """Emit a pyLSD SHIH command line for a 1H chemical shift.

        Args:
            atom_idx: Atom index (1-based)
            shift: 1H chemical shift in ppm

        Returns:
            String like "SHIH 10 3.71"
        """
        return f"SHIH {atom_idx} {shift:.2f}"

    @staticmethod
    def generate(problem: LSDProblem) -> str:
        """Generate LSD input file content from problem definition.

        Args:
            problem: Complete LSD problem with atoms and correlations

        Returns:
            String content of LSD input file
        """
        lines = []

        # Header comments
        lines.append(f"; LSD input file: {problem.name}")
        lines.append("; Generated by ailsa")
        if problem.molecular_formula:
            lines.append(f"; Molecular formula: {problem.molecular_formula}")
        for comment in problem.comments:
            lines.append(f"; {comment}")
        lines.append("")

        # pyLSD header commands (FORM, ELIM) — only when pylsd_mode enabled
        if problem.pylsd_mode:
            if problem.molecular_formula:
                lines.append(LSDInputGenerator.emit_form(problem.molecular_formula))
            for n, m in problem.elim_commands:
                lines.append(LSDInputGenerator.emit_elim(n, m))
            if problem.molecular_formula or problem.elim_commands:
                lines.append("")

        # Global ELIM budget (Phase 80 D-01/D-02: primary 4J mechanism)
        # Independent of pylsd_mode — emits ELIM N 0 when elim_budget > 0
        if problem.elim_budget > 0:
            lines.append(LSDInputGenerator.emit_elim(problem.elim_budget, 0))
            lines.append("")

        # Atom definitions (MULT commands)
        if problem.atoms:
            lines.append("; Atom definitions")
            for atom in sorted(problem.atoms, key=lambda a: a.index):
                lines.append(atom.to_mult_line())
            lines.append("")

        # Chemical shifts (SHIX for 13C, SHIH for 1H)
        shifts_added = False
        for atom in sorted(problem.atoms, key=lambda a: a.index):
            if atom.carbon_shift is not None:
                if not shifts_added:
                    lines.append("; Chemical shifts")
                    shifts_added = True
                lines.append(f"SHIX {atom.index} {atom.carbon_shift:.2f}")
        # SHIH: 1H shifts for atoms with proton_shift set
        for atom in sorted(problem.atoms, key=lambda a: a.index):
            if atom.proton_shift is not None:
                if not shifts_added:
                    lines.append("; Chemical shifts")
                    shifts_added = True
                lines.append(LSDInputGenerator.emit_shih(atom.index, atom.proton_shift))
        if shifts_added:
            lines.append("")

        # Group correlations by type
        hsqc_corrs = [c for c in problem.correlations if c.correlation_type in ("HSQC", "HMQC")]
        hmbc_corrs = [c for c in problem.correlations if c.correlation_type == "HMBC"]
        cosy_corrs = [c for c in problem.correlations if c.correlation_type == "COSY"]

        # HSQC correlations
        if hsqc_corrs:
            lines.append("; Direct C-H correlations (HSQC)")
            for corr in hsqc_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # HMBC correlations
        if hmbc_corrs:
            lines.append("; Long-range C-H correlations (HMBC)")
            for corr in hmbc_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # COSY correlations
        if cosy_corrs:
            lines.append("; H-H correlations (COSY)")
            for corr in cosy_corrs:
                lines.append(corr.to_lsd_line())
            lines.append("")

        # Structural constraints (BOND/FBND)
        bond_constraints = [c for c in problem.constraints if c.constraint_type == "BOND"]
        fbnd_constraints = [c for c in problem.constraints if c.constraint_type == "FBND"]

        if bond_constraints:
            lines.append("; Required bonds (derived from spectroscopic data)")
            for constraint in bond_constraints:
                comment = f"  ; {constraint.reason}" if constraint.reason else ""
                lines.append(f"{constraint.to_lsd_line()}{comment}")
            lines.append("")

        if fbnd_constraints:
            lines.append("; Forbidden bonds")
            for constraint in fbnd_constraints:
                comment = f"  ; {constraint.reason}" if constraint.reason else ""
                lines.append(f"{constraint.to_lsd_line()}{comment}")
            lines.append("")

        # Ring exclusion (DEFF F / FEXP) — filter files written by write_file().
        # generate() emits relative paths; write_file() copies ring3/ring4 to output_dir.
        # LSD resolves relative DEFF paths from its CWD (always output_dir, per Phase-73
        # runner contract).  No DEFF NOT is ever emitted — D-03 native-only contract.
        if problem.ring_exclusion_enabled:
            lines.append("; Ring exclusion filters")
            lines.append('DEFF F1 "ring3"')
            lines.append('DEFF F2 "ring4"')
            lines.append('FEXP "NOT F1 AND NOT F2"')
            lines.append("")

        # End marker
        lines.append("EXIT")

        return "\n".join(lines)

    @staticmethod
    def write_file(problem: LSDProblem, output_path: Path | str) -> Path:
        """Write LSD input file to disk.

        When ring_exclusion_enabled is True, also copies the bundled ring3/ring4
        filter files to the same directory as the .lsd file.  LSD is invoked with
        cwd=output_dir (Phase-73 runner contract), so the relative DEFF paths
        "ring3" and "ring4" emitted by generate() resolve correctly.

        Args:
            problem: LSD problem to write
            output_path: Path for output file

        Returns:
            Path to written file
        """
        output_path = Path(output_path)
        content = LSDInputGenerator.generate(problem)
        output_path.write_text(content)
        if problem.ring_exclusion_enabled:
            LSDInputGenerator._write_filter_files(output_path.parent)
        return output_path

    @staticmethod
    def _write_filter_files(output_dir: Path) -> None:
        """Copy bundled ring3/ring4 filter files to output_dir.

        Filter files must be co-located with the .lsd file because LSD is
        invoked with cwd=output_dir and resolves relative DEFF paths from its CWD
        (per Phase-73 runner contract).  Called by write_file() when
        ring_exclusion_enabled is True.

        Args:
            output_dir: Directory where the .lsd file will be written.
        """
        package = importlib.resources.files("ailsa.lsd.filters")
        for name in ("ring3", "ring4"):
            content = (package / name).read_text()
            (output_dir / name).write_text(content)

    @staticmethod
    def from_peak_data(
        carbon_peaks: PeakList1D,
        hsqc_peaks: PeakList2D | None = None,
        hmbc_peaks: PeakList2D | None = None,
        cosy_peaks: PeakList2D | None = None,
        dept_result: DEPTGuidedResult | None = None,
        molecular_formula: str | None = None,
        name: str = "problem",
        tolerance: float = 1.0,
    ) -> LSDProblem:
        """Build LSD problem from NMR peak data.

        Creates atom definitions from 13C peaks and correlations from 2D spectra.
        If molecular_formula is provided, adds missing carbons and heteroatoms.

        Args:
            carbon_peaks: 1D 13C peak list (defines atoms)
            hsqc_peaks: HSQC 2D peak list (optional)
            hmbc_peaks: HMBC 2D peak list (optional)
            cosy_peaks: COSY 2D peak list (optional)
            dept_result: DEPT-guided result for multiplicity info (optional)
            molecular_formula: Molecular formula string (optional)
            name: Problem name
            tolerance: ppm tolerance for peak matching

        Returns:
            LSDProblem ready for input file generation
        """
        problem = LSDProblem(
            molecular_formula=molecular_formula,
            name=name,
        )

        # Parse molecular formula to get expected atom counts
        formula_counts: dict[str, int] = {}
        if molecular_formula:
            formula_counts = parse_molecular_formula(molecular_formula)

        # Build atom index mapping: carbon ppm → atom index
        # Sort by ppm descending (high field first, as is NMR convention)
        sorted_carbons = sorted(carbon_peaks.peaks, key=lambda p: -p.position)
        ppm_to_index: dict[float, int] = {}

        atom_index = 1
        for peak in sorted_carbons:
            ppm_to_index[peak.position] = atom_index

            # Determine hybridization and H count from DEPT if available
            hybridization = Hybridization.SP3  # Default
            hydrogen_count = 0  # Default (quaternary)

            if dept_result and dept_result.carbon_multiplicities:
                # Find matching DEPT carbon
                for dept_ppm, mult in dept_result.carbon_multiplicities.items():
                    if abs(dept_ppm - peak.position) <= tolerance:
                        if mult == "CH2":
                            hydrogen_count = 2
                            hybridization = Hybridization.SP3
                        elif mult == "CH":
                            hydrogen_count = 1
                            # Use chemical shift to determine hybridization
                            # Aromatic/olefinic CH: ~100-160 ppm = sp2
                            # Aliphatic CH: ~10-80 ppm = sp3
                            if 100 <= peak.position <= 160:
                                hybridization = Hybridization.SP2
                            else:
                                hybridization = Hybridization.SP3
                        elif mult == "CH3":
                            hydrogen_count = 3
                            hybridization = Hybridization.SP3
                        elif mult == "CH/CH3":
                            # Ambiguous from DEPT-135 alone
                            # Use chemical shift heuristics:
                            # - 0-30 ppm: likely CH3 (alkyl methyl)
                            # - 30-60 ppm: likely CH (methine)
                            # - 100-160 ppm: CH (aromatic/olefinic)
                            if peak.position < 30:
                                hydrogen_count = 3  # Likely CH3
                                hybridization = Hybridization.SP3
                            elif 100 <= peak.position <= 160:
                                hydrogen_count = 1  # Aromatic CH
                                hybridization = Hybridization.SP2
                            else:
                                hydrogen_count = 1  # Likely CH
                                hybridization = Hybridization.SP3
                        break

            atom = LSDAtom(
                index=atom_index,
                element="C",
                hybridization=hybridization,
                hydrogen_count=hydrogen_count,
                carbon_shift=peak.position,
            )
            problem.add_atom(atom)
            atom_index += 1

        # Add missing carbons from molecular formula (quaternary carbons not in DEPT)
        observed_carbons = len(sorted_carbons)
        expected_carbons = formula_counts.get("C", 0)
        missing_carbons = expected_carbons - observed_carbons

        for _ in range(missing_carbons):
            atom = LSDAtom(
                index=atom_index,
                element="C",
                hybridization=Hybridization.SP2,  # Quaternary carbons often sp2
                hydrogen_count=0,
            )
            problem.add_atom(atom)
            atom_index += 1

        # Calculate total hydrogens assigned to carbons
        carbon_assigned_h = sum(a.hydrogen_count for a in problem.atoms if a.element == "C")
        expected_h = formula_counts.get("H", 0)
        missing_h = expected_h - carbon_assigned_h

        # Identify carbonyl carbons from chemical shift and update hybridization
        # Carboxylic acids/esters: 165-185 ppm
        # Aldehydes/ketones: 190-220 ppm
        # Amides: 160-180 ppm
        carbonyl_atoms: list[LSDAtom] = []
        for i, atom in enumerate(problem.atoms):
            if atom.element == "C" and atom.carbon_shift is not None:
                # Carbonyl detection: quaternary carbon with shift in carbonyl range
                if atom.hydrogen_count == 0 and (
                    (165 <= atom.carbon_shift <= 185) or  # acids, esters, amides
                    (190 <= atom.carbon_shift <= 220)  # aldehydes, ketones
                ):
                    carbonyl_atoms.append(atom)
                    # Update hybridization to SP2 for carbonyl carbons
                    problem.atoms[i] = LSDAtom(
                        index=atom.index,
                        element=atom.element,
                        hybridization=Hybridization.SP2,
                        hydrogen_count=atom.hydrogen_count,
                        charge=atom.charge,
                        carbon_shift=atom.carbon_shift,
                        proton_shift=atom.proton_shift,
                    )

        # Add heteroatoms from molecular formula
        heteroatom_defaults = {
            "N": (Hybridization.SP3, 1),  # Nitrogen: often sp3 with 1H
            "S": (Hybridization.SP3, 0),  # Sulfur
            "P": (Hybridization.SP3, 0),  # Phosphorus
            "Cl": (Hybridization.SP3, 0),  # Chlorine
            "Br": (Hybridization.SP3, 0),  # Bromine
            "F": (Hybridization.SP3, 0),  # Fluorine
            "I": (Hybridization.SP3, 0),  # Iodine
        }

        # Handle oxygen with spectroscopic inference:
        # 1. For each carbonyl carbon, pair with an sp2 oxygen (C=O)
        # 2. Remaining oxygens are sp3 (hydroxyl/ether)
        # 3. Missing H from MF goes to sp3 oxygens
        oxygen_count = formula_counts.get("O", 0)
        num_carbonyls = min(len(carbonyl_atoms), oxygen_count)
        num_sp3_oxygen = oxygen_count - num_carbonyls

        # Create oxygen atoms and track indices for BOND constraints
        sp2_oxygen_indices: list[int] = []
        sp3_oxygen_indices: list[int] = []

        # Add sp2 oxygens (carbonyl)
        for _ in range(num_carbonyls):
            sp2_oxygen_indices.append(atom_index)
            atom = LSDAtom(
                index=atom_index,
                element="O",
                hybridization=Hybridization.SP2,
                hydrogen_count=0,
            )
            problem.add_atom(atom)
            atom_index += 1

        # Add sp3 oxygens (hydroxyl/ether)
        # Assign missing H to these oxygens
        h_to_assign = missing_h
        for _ in range(num_sp3_oxygen):
            sp3_oxygen_indices.append(atom_index)
            # If we have missing H, assign one to this oxygen (makes it a hydroxyl)
            h_on_this_o = 1 if h_to_assign > 0 else 0
            if h_to_assign > 0:
                h_to_assign -= 1
            atom = LSDAtom(
                index=atom_index,
                element="O",
                hybridization=Hybridization.SP3,
                hydrogen_count=h_on_this_o,
            )
            problem.add_atom(atom)
            atom_index += 1

        # Create BOND constraints: pair carbonyl carbons with sp2 oxygens
        for i, carbonyl_c in enumerate(carbonyl_atoms[:num_carbonyls]):
            problem.add_constraint(LSDConstraint(
                atom1_index=carbonyl_c.index,
                atom2_index=sp2_oxygen_indices[i],
                constraint_type="BOND",
                reason=f"carbonyl C ({carbonyl_c.carbon_shift:.1f} ppm) double-bonded to O",
            ))

        # Handle other heteroatoms
        for element, count in formula_counts.items():
            if element in heteroatom_defaults:
                hyb, h_count = heteroatom_defaults[element]
                for _ in range(count):
                    atom = LSDAtom(
                        index=atom_index,
                        element=element,
                        hybridization=hyb,
                        hydrogen_count=h_count,
                    )
                    problem.add_atom(atom)
                    atom_index += 1

        # Helper to find atom index for a ppm value
        def find_atom_index(ppm: float) -> int | None:
            for carbon_ppm, idx in ppm_to_index.items():
                if abs(carbon_ppm - ppm) <= tolerance:
                    return idx
            return None

        # Add HSQC correlations
        if hsqc_peaks:
            seen_hsqc: set[tuple[int, int]] = set()
            for peak in hsqc_peaks.peaks:
                atom_idx = find_atom_index(peak.f1_position)
                if atom_idx is not None:
                    # H index same as C index for direct correlation
                    key = (atom_idx, atom_idx)
                    if key not in seen_hsqc:
                        seen_hsqc.add(key)
                        problem.add_correlation(LSDCorrelation(
                            atom1_index=atom_idx,
                            atom2_index=atom_idx,
                            correlation_type="HSQC",
                        ))

        # Add HMBC correlations
        if hmbc_peaks:
            seen_hmbc: set[tuple[int, int]] = set()
            for peak in hmbc_peaks.peaks:
                # F1 is carbon, F2 is proton
                carbon_idx = find_atom_index(peak.f1_position)
                if carbon_idx is not None:
                    # For HMBC, we need to find which H position correlates
                    # The H position relates to another carbon's attached H
                    # For now, use carbon index as H reference
                    # In reality, would need proton assignment

                    # Find which carbon the proton belongs to (from HSQC)
                    h_carbon_idx = None
                    if hsqc_peaks:
                        for hsqc in hsqc_peaks.peaks:
                            if abs(hsqc.f2_position - peak.f2_position) <= 0.1:  # Proton tolerance
                                h_carbon_idx = find_atom_index(hsqc.f1_position)
                                break

                    if h_carbon_idx is not None and h_carbon_idx != carbon_idx:
                        key = (carbon_idx, h_carbon_idx)
                        if key not in seen_hmbc:
                            seen_hmbc.add(key)
                            problem.add_correlation(LSDCorrelation(
                                atom1_index=carbon_idx,
                                atom2_index=h_carbon_idx,
                                correlation_type="HMBC",
                                min_bonds=2,
                                max_bonds=3,
                            ))

        # Add COSY correlations
        if cosy_peaks:
            seen_cosy: set[tuple[int, int]] = set()
            for peak in cosy_peaks.peaks:
                # Both F1 and F2 are protons - need to map to carbons via HSQC
                if hsqc_peaks:
                    h1_carbon = None
                    h2_carbon = None

                    for hsqc in hsqc_peaks.peaks:
                        if abs(hsqc.f2_position - peak.f1_position) <= 0.1:
                            h1_carbon = find_atom_index(hsqc.f1_position)
                        if abs(hsqc.f2_position - peak.f2_position) <= 0.1:
                            h2_carbon = find_atom_index(hsqc.f1_position)

                    if h1_carbon and h2_carbon and h1_carbon != h2_carbon:
                        key = tuple(sorted([h1_carbon, h2_carbon]))
                        if key not in seen_cosy:
                            seen_cosy.add(key)
                            problem.add_correlation(LSDCorrelation(
                                atom1_index=key[0],
                                atom2_index=key[1],
                                correlation_type="COSY",
                            ))

        return problem

    @staticmethod
    def from_dept_result(
        dept_result: DEPTGuidedResult,
        hmbc_peaks: PeakList2D | None = None,
        cosy_peaks: PeakList2D | None = None,
        molecular_formula: str | None = None,
        name: str = "problem",
        tolerance: float = 1.0,
    ) -> LSDProblem:
        """Build LSD problem from DEPT-guided result.

        Convenience method that uses DEPT result as primary source.

        Args:
            dept_result: Result from DEPTGuidedPicker
            hmbc_peaks: HMBC 2D peak list (optional)
            cosy_peaks: COSY 2D peak list (optional)
            molecular_formula: Molecular formula string
            name: Problem name
            tolerance: ppm tolerance for matching

        Returns:
            LSDProblem ready for input file generation
        """
        return LSDInputGenerator.from_peak_data(
            carbon_peaks=dept_result.dept_peaks,
            hsqc_peaks=dept_result.peaks,
            hmbc_peaks=hmbc_peaks,
            cosy_peaks=cosy_peaks,
            dept_result=dept_result,
            molecular_formula=molecular_formula,
            name=name,
            tolerance=tolerance,
        )


def validate_pylsd_input(problem: LSDProblem) -> None:
    """Validate pyLSD-format problem for FORM/MULT consistency.

    Only checks carbon count (not heteroatoms — oxygen count is
    deliberately ambiguous due to hydroxyl/ether flexibility).

    Args:
        problem: LSD problem to validate

    Raises:
        ValueError: If FORM carbon count does not match MULT carbon count.
    """
    if problem.molecular_formula is None:
        return
    formula_counts = parse_molecular_formula(problem.molecular_formula)
    form_c = formula_counts.get("C", 0)
    mult_c = sum(1 for a in problem.atoms if a.element == "C")
    if form_c != mult_c:
        raise ValueError(
            f"FORM/MULT mismatch: FORM declares {form_c} carbons "
            f"but MULT defines {mult_c} carbons in '{problem.molecular_formula}'"
        )


def detect_aromatic_cosy_pairs(
    groups: list[SignalGroup],
    aromatic_range: tuple[float, float] = (100.0, 165.0),
) -> list[tuple[int, int]]:
    """Derive cross-ring COSY equivalence pairs for aromatic CH groups.

    For two groups of aromatic sp2 CH atoms detected by ailsa analyze grouping,
    pairs them cross-ring using the reversed-sort algorithm. Verified reference:
    arm_a.lsd (.planning/phases/72-design-re-validation/experiment/arm_a.lsd)
    → COSY 4 7 + COSY 5 6 → 2/2 aromatic solutions (ibuprofen present).

    Algorithm: zip(sorted(groupA.atom_ids), reversed(sorted(groupB.atom_ids)))
    This produces cross-group pairing (NEVER within-group), preventing LSD
    error 283 when ring BONDs are also present.

    For ibuprofen example:
    - Group A: shifts [129.38, 129.38], atom_ids [4, 5]
    - Group B: shifts [127.26, 127.26], atom_ids [6, 7]
    - zip(sorted([4,5]), reversed(sorted([6,7]))) = zip([4,5], [7,6]) = [(4,7), (5,6)]
    - Yields COSY 4 7 + COSY 5 6 (exactly the Arm A reference)

    Args:
        groups: SignalGroup list from group_signals() (ailsa analyze grouping output).
                atom_ids are 1-based (LSD convention).
        aromatic_range: ppm range for aromatic sp2 CH carbon shifts.
                        Default (100.0, 165.0) covers all aromatic carbons.

    Returns:
        List of (atom1_id, atom2_id) tuples — 1-based, ready for
        LSDProblem.add_aromatic_equivalence_pair(). Empty list if fewer than
        2 aromatic groups of equal size are present.
    """
    # Filter groups where ALL shifts fall within the aromatic range
    aromatic_groups = [
        g for g in groups
        if all(aromatic_range[0] <= s <= aromatic_range[1] for s in g.shifts)
    ]

    pairs: list[tuple[int, int]] = []
    used: set[int] = set()

    for i, ga in enumerate(aromatic_groups):
        if i in used:
            continue
        for j, gb in enumerate(aromatic_groups):
            if j <= i or j in used:
                continue
            if len(ga.atom_ids) == len(gb.atom_ids) and len(ga.atom_ids) >= 2:
                # Cross-ring pairing: sort group A ascending, sort group B descending
                # zip produces cross-ring pairs (a_ids[0] with b_ids[-1], etc.)
                a_ids = sorted(ga.atom_ids)
                b_ids = list(reversed(sorted(gb.atom_ids)))
                pairs.extend(zip(a_ids, b_ids, strict=True))
                used.add(i)
                used.add(j)
                break

    return pairs
